### ISSUE TITLE
Fix API multi-language function

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#116]
# What

APIの中で他言語対応している部分に`params[:lang]`を用いているが、これだと言語が指定されなかった時の挙動が想定していたものとずれてしまうので修正する

**Comment by hikalium** [comment]
app/models/contest.rb のname_and_descriptionとかにnilが指定された場合に日本語とみなす、という方法で修正する予定ですか？（それならいいのだけど）
