### ISSUE TITLE
Secure admin page

### ISSUE THREAD

**Issue by hikalium** [ProgrammingDaisukiClub/WPCS2#136]
admin/sign_upが誰でもできてしまうので、実運用ではこれをなんとかする。

**Comment by ShinyaKato** [comment]
18日は問題を直接DBに流すので、Adminへのroutesは落としてしまう

**Comment by ShinyaKato** [comment]
やっぱり、basic認証かけることにした

**Comment by ShinyaKato** [comment]
いや、publicなレポジトリだからID/Passを直書きするわけにはいかないな
本番って環境変数設定できるんだろうか？

**Comment by hikalium** [comment]
環境変数は設定できるはず。

**Comment by ShinyaKato** [comment]
それは何で設定することになるの？

**Comment by hikalium** [comment]
herokuのコンフィグページ。だから外からは見えない。

**Comment by ShinyaKato** [comment]
なら、OK
