### ISSUE TITLE
Make queries to find prize winners

### ISSUE THREAD

**Issue by exKAZUu** [ProgrammingDaisukiClub/WPCS2#239]

**Comment by hikalium** [comment]
+ 総合得点上位1-9位: プレゼント(物)をひとつえらべる
+ 総合得点上位10-15位: よく頑張りました賞（図書カード500円）
+ 総合得点上位16, 32, 64位: 2^n賞(図書カード500円)
+ 上記以外の人に対して
  + Last Large AC賞x8（コンテスト時間内の最後に各問題でLargeをACした人に与えられる）
  + First All Small 賞x1（最初にsmallをすべて解いた人に与えられる）
