### ISSUE TITLE
【管理者向け】コンテスト問題の JSON アップロード機能

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#259]
## 概要

管理者ページに JSON 形式で問題をアップロードできるようにする。

#### 使い方のイメージ

1. 管理者ページでコンテストを作成。
2. コンテストの編集ページで全問題のデータを含んだ JSON をアップロードする。

JSON は別途スクリプトを書いてもらって生成する予定。
アップロードするたびに problems のレコードは全書き換えする。

#### TODO

- [x] JSON 形式の決定

**Comment by tossy310** [comment]
@ShinyaKato 
こんな形でjsonを出力でどうでしょう。
http://www.yama.info.waseda.ac.jp/~hsato/sample.json

簡単に言うと、以下のようなフォーマット。
```json
{
  "contest_name": "Sample Contest",
  "problems": [
    {
      "title": "A + B",
      "statement": "# Description\n\n2つの整数 $A, B$ の和を求めよ。\n\nほげ。\n",
      "data_sets": [
        {
          "label": "Small",
          "score": 50,
          "input": "2\n1 2\n3 4\n",
          "output": "3\n7\n"
        },
        ....
      ]
    },
    ....
  ]
}
```
