### ISSUE TITLE
Generate Models

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#26]
### アイディアラフ

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/13827377/22697606/4fd6a906-ed95-11e6-8c5b-bcb33b1891c9.jpg)

### 主なモデル

* User
* Contest
* Problem
* Submission
* ContestRegistration(ユーザーとコンテストの中間テーブル)

### TODO

* 各モデルに必要なカラムの洗い出し
* migration作る

**Comment by ShinyaKato** [comment]
### Problem

| カラム名           | 型      | NULL  | 補足         |                |
|--------------------|---------|-------|--------------|----------------|
| contest_id         | integer | FALSE | コンテストID |                |
| name               | string  | FALSE | 問題名       |                |
| statement          | text    | FALSE | 問題文       |                |
| constraints        | text    |       | 制約         |                |
| input_description  | text    | FALSE | 入力         |                |
| output_description | text    | FALSE | 出力         |                |
| note               | text    |       | 補足         |                |
| example            | text    | FALSE | 入出力例     | 複数存在する？ |
| order              | integer | FALSE | 問題の表示順 |                |
| score              | integer | FALSE | 得点         |                |

**Comment by ShinyaKato** [comment]
### Contest

| カラム名    | 型       | NULL  | 補足             |
|-------------|----------|-------|------------------|
| name        | string   | FALSE | コンテスト名     |
| description | text     | FALSE | コンテスト説明文 |
| start_at    | datetime | FALSE | 開始日時         |
| end_at      | datetime | FALSE | 終了日時         |

**Comment by ShinyaKato** [comment]
### Submission

| カラム名        | 型      | NULL  | 補足         |
|-----------------|---------|-------|--------------|
| user_id         | integer | FALSE | ユーザーID   |
| problem_id      | integer | FALSE | 問題ID       |
| answer          | text    | FALSE | 解答         |
| code            | text    |       | ソースコード |
| language_id     | integer |       | 使用言語     |
| judge_status_id | integer | FALSE | ジャッジ結果 |

**Comment by ShinyaKato** [comment]
### User

| カラム名    | 型     | NULL  | 補足           |
|-------------|--------|-------|----------------|
| name        | string | FALSE | ユーザー名     |
| email       |        |       |                |
| password    |        |       |                |
| profile     | text   |       | プロフィール？ |
| affiliation | string |       | 所属           |

**Comment by ShinyaKato** [comment]
### ContestResigtration

| カラム名   | 型      | NULL  | 補足         |
|------------|---------|-------|--------------|
| user_id    | integer | FALSE | ユーザーID   |
| contest_id | integer | FALSE | コンテストID |

**Comment by hikalium** [comment]
### TestCase

| カラム名   | 型      | NULL  | 補足         |
|------------|---------|-------|--------------|
| case_id    | integer | FALSE | テストケースID   |
| case_name    | integer | FALSE | テストケース名(Large, Small等？)   |
| problem_id | integer | FALSE | このテストケースが含まれる問題ID |
| input | text | FALSE | 入力データ（ユーザーがダウンロードできる） |
| output | text | FALSE | 出力データ（ユーザーの送信してきた結果と比較する） |
| score              | integer | FALSE | 得点         |
| accuracy              | integer | FALSE | 結果が浮動小数点の場合の精度(0で完全一致)  |
