### ISSUE TITLE
コンテスト参加にパスワードを付ける機能の追加

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#261]
## 概要

オンサイトでの参加者にのみ参加を許す場合など、パスワードを口頭で伝えてそれを入力してコンテストに参加と言った使い方を想定している。

オープンコンテストとの差別化のためにデザインの色を変えるなどしたい。

**Comment by getty104** [comment]
オープンコンテストとの差別化のためにデザインの色を変えるなどしたい。
は別のissueっぽかったので分けた

**Comment by getty104** [comment]
フロント：
参加者：パスワードフォーム
コンテスト作成者：パスワードつけるチェックボックス

バック：
参加者：パスワード認証
コンテスト作成者：パスワード設定

**Comment by getty104** [comment]
これ思ったけどBasic認証使えば良さそう。
流れ的には
1. コンテスト作成画面に、内部生向けフラグのチェックボタンにチェックする
2. フラグがある場合は、コンテストを選んだ時にBasic認証が出てくる

認証のユーザー名とパスワードはENVで設定する

実装するもの
1. contestモデルへの、内部生向けフラグのカラム
2. コンテスト作成フォームへの内部生向けフラグのチェックボタン
3. コントローラーへのBasic認証用ロジック（controllers/application.rbと同じ感じ）

**Comment by getty104** [comment]
@Shikugawa 
やっぱりBasic認証じゃなくて機能作ろう by Shinya Kato

**Comment by Shikugawa** [comment]
@getty104 @ShinyaKato ちゃんと機能作るとなるとどんな感じにすればいいですかね？

**Comment by Shikugawa** [comment]
鍵付きコンテストにパスワードを作っておいて、コンテスト一覧から鍵付きコンテストを選択したらログインフォームっぽいのが出てきてそこにコンテストのパスワードを入力して実際のコンテスト画面に遷移するような構成にするとしたら、コンテストのパスワードは環境変数として指定しておくようにするならバックエンド側はコンテストのステータスカラム(0の時内部生向け、1の時外部生向け。コンテストに応じて色を変更する際に使うだけ)を追加するだけで、あとは全部フロント側で実装するという感じにするのがいいと思うんですけど
