### ISSUE TITLE
コンテストの種類ごとにヘッダーの色を変えたい

### ISSUE THREAD

**Issue by getty104** [ProgrammingDaisukiClub/WPCS2#268]
コンテストの種類でヘッダーの色を変えたい

**Comment by getty104** [comment]
内部向けフラグの実装
フラグによってヘッダーの色を変える

**Comment by getty104** [comment]
パスワード機能の方の内部生向けフラグを使えば良さそう

**Comment by getty104** [comment]
@musaprg パスワード機能が実装されたから次これおなしゃす

**Comment by musaprg** [comment]
@getty104 了解しました

**Comment by ShinyaKato** [comment]
@musaprg 

ヘッダーに色を付けて、外部向けと内部向けの色を変えることにしよう

現状:
![_2018_05_08_16_53](https://user-images.githubusercontent.com/13827377/39744808-6159ec22-52e0-11e8-9101-054999e68834.png)


外部向け:
![_2018_05_08_16_49](https://user-images.githubusercontent.com/13827377/39744660-fd0f6ef4-52df-11e8-9523-d15facb8ec77.png)

内部向け:
#42b361
![_2018_05_08_16_52](https://user-images.githubusercontent.com/13827377/39744749-3f3d5318-52e0-11e8-8fe1-b04b934ac8e0.png)
