### ISSUE TITLE
サーバー側を書き換える度に毎回docker buildを走らせるのがだるい

### ISSUE THREAD

**Issue by musaprg** [ProgrammingDaisukiClub/WPCS2#403]

**Comment by Shikugawa** [comment]
これは解決したいけどなんかいい方法ある？

**Comment by musaprg** [comment]
compose経由の起動の場合で使用するスクリプト(frontも変更を監視して自動でビルドし直すようにする)を組んだ上で、ホスト側のボリュームを直接マウントするようにするのがよさそう

**Comment by musaprg** [comment]
とはいえ時間かかってるのはやっぱりbundle installな気がしている。現状だとRails関連のファイルを更新した場合もbuildが必要なので、根本的には↓の対応をするしかない気がする

https://github.com/ProgrammingDaisukiClub/WPCS2/pull/375#discussion_r418979870
