### ISSUE TITLE
Add Rspec

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#51]
Minitestでいきます？
Rspecにします？

**Comment by exKAZUu** [comment]
@junk0612 何か意見はあるだろうか？個人的には、Minitestのままでええんやないかと思っている。

**Comment by ShinyaKato** [comment]
Rspecはお情け程度で使ったことあるけれど、Minitestは使ったことないですねぇ
(正直そんなにRailsのテスト書くことなさそうではある)

**Comment by exKAZUu** [comment]
よし、俺がテスト書きまくってPR妨害するマンになろう

**Comment by junk0612** [comment]
うーん。自分もわりとどっちでもいいんですが、強いて言うならシナリオテストは RSpec + Capybara のほうが書きやすそうではある感じですかね。
あと、3月分には間に合わなければテスト省いてもいいかもしれないですけど、なるべくテストは書いたほうがいいですよ。
(というか、テストまで含めた PR を作るのが理想だと思っている)

**Comment by exKAZUu** [comment]
CapybaraはRspecでも、Minitestでも、どっちからでも使えるよ。（そもそも、テスティングフレームワークに非依存。）

**Comment by junk0612** [comment]
あー、それはそうなんですが、Capybara の DSL がかなり RSpec っぽいんですよ。Minitest はもともと BDD 向けじゃないので、若干無理したテストコードになりそうだなと思っています。

**Comment by exKAZUu** [comment]
まぁそれはそうね。じゃぁBDDスタイルにするか。

**Comment by junk0612** [comment]
RSpec は RSpec で学習コスト高いのが難点ですけどね 😓

**Comment by exKAZUu** [comment]
三人とも体験しているので、まぁ、大丈夫だと思われる。

**Comment by junk0612** [comment]
こいつ引き取って PR 作っちゃいますねー
