### ISSUE TITLE
Admin authentication

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#56]
# Why

管理者用ページがログインしなくても見れてしまう

# What

ログインしていなければリダイレクトさせる

# How

`AdminControllerBase`を用意し`before_action`でログインしているかどうかをチェックする
管理者用ページのコントローラーは必ずこのクラスを継承するようにする

**Comment by junk0612** [comment]
管理者としてログインしていない場合のリダイレクト先は管理者用ログインページという理解で良い？

**Comment by ShinyaKato** [comment]
で、いいんじゃないですかね

**Comment by ShinyaKato** [comment]
と言うか、今思ったんですけどAdminって普通に登録できたらまずいんじゃ

**Comment by junk0612** [comment]
その通りですな。
View は作らずにコンソールから作るだけの対応にするか、Super Admin みたいなのを作ってその人の許可を受ける形にするかあたりがぱっと思いつく対処法だろうか

**Comment by ShinyaKato** [comment]
ちゃんと作るとしたら招待制(メアド入力するとそのアドレスにワンタイムトークン付きの登録ページのURLが飛ぶ)にするのが良いのかなぁと
まぁ、でも今はコンソールから作るだけでもいいかも
