### ISSUE TITLE
API specification

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#61]
## 進捗一覧
- Status
  - (blank)
  - WIP: spec
  - waiting for: impl
  - WIP: impl
  - done

|Status| HTTP method | URI                           | description                        |
| --- |-------------|-------------------------------|------------------------------------|
| done | GET         | /api/contents/:id             | コンテストの情報(問題も含め)を返す |
| done | POST        | /api/contests/:id/entry       | コンテストに参加する               |
| | POST        | /api/contests/:id/submissions | 解答を提出する                     |
| waiting for: impl | GET         | /api/contests/:id/ranking     | ランキング情報を返す               |
| | GET         | /api/contests/:id/submissions | Submissionsの一覧を取得する(一旦後回し)   |

**Comment by ShinyaKato** [comment]
# 本日のノート

![img_0724](https://cloud.githubusercontent.com/assets/13827377/23126226/0945d0b0-f7b9-11e6-91bb-92d1c7261118.JPG)

![img_0725](https://cloud.githubusercontent.com/assets/13827377/23126229/0ea60ea8-f7b9-11e6-8308-66ea1d07e524.JPG)

**Comment by ShinyaKato** [comment]
# GET /api/contents/:id

## Case 1

idで指定されたContestが存在しない:
=> HTTP status 404

## Case 2

ユーザーがログインしていない:
ユーザーがログインしている and コンテスト終了前 and コンテストに参加していない:
ユーザーがログインしている adn コンテスト開始前 and コンテストに参加している:
=> HTTP status 200, bodyでコンテストの情報のみ返す

```js
{
  id: 1, // あってもなくてもいいかなぁ...
  name: "コンテスト名",
  description: "コンテスト詳細説明",
  joined: false // コンテストに参加しているか否か
}
```

## Case 3

コンテスト期間中 and コンテストに参加している:
コンテスト終了後:
=> HTTP status 200, bodyでコンテストと問題/データセットの情報を返す

```js
{
  id: 1, // あってもなくてもいいかなぁ...
  name: "コンテスト名",
  description: "コンテスト詳細説明",
  problems: [
    {
      id: 1,
      name: "問題名",
      description: "問題詳細",
      data_sets: [
        id: 1,
        label: "Small",
        score: 100
      ],
    },
  ],
  joined: false // コンテストに参加しているか否か
}
```

**Comment by ShinyaKato** [comment]
# POST /api/contests/:id/entry

## Case 1

idで指定されたコンテストが存在しない場合:
=> Http status 404

## Case 2

ユーザーがログインしていない場合:
=> Http status 403

## Case 3

すでに登録済み(レコードが存在する)場合:
=> Http status 409

## Case 4

コンテスト終了後の場合:
=> Http status 403

## Case 5

登録に成功した場合:
=> Http status 201

**Comment by ShinyaKato** [comment]
# POST /api/contests/:id/submissions

## Case 1

idで指定されたコンテストが存在しない場合:
=> Http status 404

## Case 2

ユーザーがログインしていない場合:
コンテスト開始前:
コンテスト期間中 and コンテストに参加していない場合:
=> Http status 403

## Case 3

コンテスト期間中 and コンテストに参加している場合:
コンテスト終了後:
=> Http status 201, bodyで作成されたsubmissionsのレコードを返す

```js
{
  id: 1,
  judge: 1, // 未確定
  score: 82 // 未確定
}
```

**Comment by ShinyaKato** [comment]
# GET /api/contests/:id/ranking

## Case 1

idで指定されたコンテストが存在しない:
=> Http status 404

## Case 2

ユーザーがログインしていない場合:
コンテスト開始前:
コンテスト期間中 and コンテストに参加していない場合:
=> Http status 403

## Case 3

コンテスト期間中 and コンテストに参加している場合:
コンテスト終了後:
=> Http status 200, bodyでranking情報を返す

```js
{
  users: [
    id: 1,
    name: "ユーザー名",
    problems: {
      1: {
        data_sets: {
          1: 75,
          2: 92
        },
      },
      2: {
        data_sets: {
          3: 35,
          4: 67
        }
      }
    }
  ]
}
```

**Comment by exKAZUu** [comment]
# GET /api/contests/:id/submissions

## Case 1

idで指定されたコンテストが存在しない場合:
=> Http status 404

## Case 2

ユーザーがログインしていない場合:
コンテストに参加していない場合:
=> Http status 403

## Case 3

ユーザーがログインしている and コンテストに参加している:
=> Http status 201, submissionsのレコードを返す

```js
[
  {
    "id": 1,
    "correct": true,
    "score": 82
  },
  {
    "id": 2,
    "correct": false
  }
]
```

**Comment by RYOSKATE** [comment]
/api/contents/:id
/api/contests/:id/entry
を実装したのですがPOST /api/contests/:id/entryの
テストの403や409のチェックってうまく動いてなかったりしませんかね？
```
def entry
 render(json: {}, status: 403)
end
```
とかだけにしてもRspecが
expected the response to have status code 403 but it was 200
と言ってくるのですが...

**Comment by ShinyaKato** [comment]
APIは実装終わってるのでCloseします
