### ISSUE TITLE
BUG?: ログインされている状態に到達できない

### ISSUE THREAD

**Issue by kumachan-mis** [ProgrammingDaisukiClub/WPCS2#674]
- アカウント登録をしようとしてもアカウント確認メールが飛んでこない
- 既にアカウントがある可能性を疑って，パスワードを変更しようとしてもできない

現象に遭遇したので報告します．

以下の手順で操作をし，現象を観測しました．どのようにしてもログイン状態にできず詰んでいます．

- STEP1: アカウント登録をしようと https://wpcs2.herokuapp.com/users/sign_up からフォームを送信してもアカウント確認メールが飛んでこない
- STEP2: https://wpcs2.herokuapp.com/users/confirmation/new から再度アカウント確認メールを飛ばそうとしても「メールアドレスは登録されています」と出る
- STEP3:  https://wpcs2.herokuapp.com/users/sign_in  からSTEP1で登録したメールアドレスとパスワードでログインしようとしても「メールアドレスまたはパスワードが不正です」と出る
- STEP4: 大学のメールアドレスを使ってアカウント登録をしようとしたので，自分が参加者だった時に作ったアカウントが既にあって上記の問題が起こっている可能性を考えた．https://wpcs2.herokuapp.com/users/password/new からパスワードを変更しようとしたが，確認メールの再送ボタンを押したところ，以下のメッセージが出た（Rails によるデフォルトののエラー表示にみえる）
<img width="545" alt="error" src="https://user-images.githubusercontent.com/29433058/117527579-0da3d600-b008-11eb-8961-4391908d8c32.png">

**Comment by musaprg** [comment]
https://www.bokukoko.info/entry/2020/12/07/080000 これかね？たぶん

**Comment by musaprg** [comment]
APIキーを使用するようになってないっぽいので修正します
