### ISSUE TITLE
BUG: 数式の \neq が正常に表示されない

### ISSUE THREAD

**Issue by kumachan-mis** [ProgrammingDaisukiClub/WPCS2#681]
https://wpcs2.herokuapp.com/contests/8/problems/51
の `知っている動物 N 種類の名前はすべて異なる` のところを見て欲しいです

どうやら数式はその部分だけ katex を呼び出して変換しているように見えます。
(https://github.com/ProgrammingDaisukiClub/WPCS2/search?q=katex&type=code) 

katex は v0.10.1 を使っているように見えるのだけれど、
katex はこのバージョンで \neq のバグを修正しているようで、ちょうどホットなところっぽいです。
実はまだバグが残っていて、うまく表示されていないという可能性があるかなと思いました。

新しいものだと
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.3/katex.min.{js,css}
が存在するようなので、ひとまずアップデートしてみてはどうでしょうかー？

**Comment by musaprg** [comment]
指摘の通りっぽいです
https://github.com/KaTeX/KaTeX/issues/1842#issuecomment-467857301

**Comment by kumachan-mis** [comment]
やっぱりそうか
アップデートよろしくです

**Comment by musaprg** [comment]
@kumachan-mis どうやらバージョンの問題じゃなくてreset.scss内のフォント設定にありそうです。KaTeXはあんまり関係なさそう

**Comment by kumachan-mis** [comment]
そうねー
まあでもアップデートしておいて損はなさそう
こちらでもコードを読んでみるので、直そう
