### ISSUE TITLE
Support multiple language

### ISSUE THREAD

**Issue by hikalium** [ProgrammingDaisukiClub/WPCS2#8]

**Comment by ShinyaKato** [comment]
URLにパラメータで`?lang=ja`とかつける形にしようかなと

で、ページのヘッダーあたりに言語切り替えボタンを用意する
(こっちはヘッダー作るときに一緒にやるのが良さそう？)

**Comment by ShinyaKato** [comment]
Reactの方の国際化どうするかの方が心配

**Comment by ShinyaKato** [comment]
Webpackのリポジトリにinternationalizationのサンプルあった
https://github.com/webpack/webpack/tree/master/examples/i18n
