### ISSUE TITLE
React Component for contests/problems#show

### ISSUE THREAD

**Issue by ShinyaKato** [ProgrammingDaisukiClub/WPCS2#86]
# What

Design: https://app.zeplin.io/project.html#pid=589e5e768caedbd5d32d87bb&sid=589e5ecd81d498c1d3151a89

Implement a React Component in `src/contests/Problem.tsx`.

## Props passed to the Component

* object: problem (problem information)
  ```
  {
    number: id, // id of the problem
    string: name, // name of the problem
    string: description, // description of the problem written in markdown
    dataSets: [
      {
        number: id, // id of the data set
        string: label, // label of the data set (e.g. small, large, etc...)
        number: score, // score of the data set (max score)
      },
      ...
    ]
  }
  ```
* function: submit(id, answer)  (callback function of answer submit)
  arguments:
  * number: id (problem id)
  * string: answer (the answer which user inputs in the submission form)

**Comment by myt588** [comment]
Please elaborate on function submit. Is submit itself a callback function? or I can call a function submit and pass in (id, answer). Is there any other specification on the function? I have finished building all the other requirements

**Comment by ShinyaKato** [comment]
@myt588 

The latter idea is correct.
> or I can call a function submit and pass in (id, answer)

Now I preparing function: `submit` which passed to `Problem` Componet.
In the function, API is accessed and `ContestApp` state is updated.
So just call function `submit` and props which your Component receive are updated properly.
(You don't consider updating state of the components.)
